### ISSUE TITLE
Multi tab support issue. 

### ISSUE THREAD

**Issue by whenkey90** [NetanelBasal/angular2-storage-sync#4]
If open the same app in two different tabs, the storage values not available in the other tab.

any fix or solution ??

**Comment by NetanelBasal** [comment]
Hey,

You can confirm please that you see the information on the console? 
`localStorage.get('yourKey')?`

**Comment by whenkey90** [comment]
If I use localStorage!
In that case, the plugin itself is not required.

**Comment by NetanelBasal** [comment]
I'm not sure I understand your problem. Behind the scenes, the plugin is using the native `localStorage` for getting/setting the values. If you saved something in one tab, it should be available in the other tab.
