### ISSUE TITLE
Local Storage data getting blank after routes to different page

### ISSUE THREAD

**Issue by srikant21** [NetanelBasal/angular2-storage-sync#5]
I am using this storage sync to retain my settings in AG-Grid(like filter,sorting and hide/show).It is working fine while doing refresh. But when i routes to some other page and come back to my grid page it is not working.My local storage sync value is coming blank.

Do u have any idea on this.Do we have to add any settings on our app.modules.ts page?
Thanks in Advance.

**Comment by NetanelBasal** [comment]
Hey, it's working with other data, or it's related to AG-Grid only?

**Comment by srikant21** [comment]
Nope..it is giving the same issue for other data.
 Do we need to define any other file like our app.modules.ts or angular-cli.json file?
Do you have any reference where u have implemented ?

**Comment by NetanelBasal** [comment]
You can please check that the data is in your localStorage by open the console and run `localStorage.get('your key')`

**Comment by NetanelBasal** [comment]
Hey, the library is deprecated, don't use it. thanks.
