### ISSUE TITLE
Doesn't work for objects

### ISSUE THREAD

**Issue by marko999** [NetanelBasal/angular2-storage-sync#6]
Works well for string except one small thing that I will mentioned in a separate issue.
But it only works for simple primitives like strings and arrays.
I have tried to use it like this:
```
@StorageSync('first', StorageStrategy.Session)
  inputObject: any = {
    inputValue: 'first'
  };
```
And html:
```
<input [(ngModel)]="inputObject.inputValue">
```

And in this case, doesn't work, could you please upgrade it to support objects too?

Thank you

**Comment by NetanelBasal** [comment]
Hey, the library is deprecated, don't use it. thanks.
