### ISSUE TITLE
On load it should try to retrieve existing value

### ISSUE THREAD

**Issue by marko999** [NetanelBasal/angular2-storage-sync#7]
For example if I have variable:
```
@StorageSync('variable')
inputVar:string
```
it should search localStorage for that variable and assign the value if exists.
That prevents some dirty additional code that needs to be done like:
```
ngOnInit(){
this.variable = localStorage.getItem('variable')
}
```

**Comment by NetanelBasal** [comment]
Hey, the library is deprecated, don't use it. thanks.
